version: '2'
volumes:
  workdir:
services:
  goat:
    build: ./app
    ports:
      - "443:443"
      - "80:80"
      - "8888:8888"
    volumes:
      - 'workdir:/usr/src/app/workdir'
    privileged: true